### ISSUE TITLE
Social might need to be updated depending on instructor interest

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/2019-01-14-uwmadison-swc#2]

**Comment by sstevens2** [comment]
Hi all,

We talked about being available for conversation and socialization during lunch both days at the pre-workshop meeting. Do we still want to plan to have a social at the end of one day too? <- If so, which day would you prefer?

@gonuke, @bam241, @cvoter, @pshriwise

Thanks,
Sarah

**Comment by cvoter** [comment]
I'm happy to be available during lunch both days. 

I'm also down for the social. Slight preference for the end of Day 1, but stronger preference for whichever day would have the most attendees (I can make either day).

**Comment by pshriwise** [comment]
I was thinking of using lunchtime as the social myself, but if we want to do both I support that too! But only in spirit as I wouldn't be able to make either day :smiley:

**Comment by gonuke** [comment]
I'm leaving town on the afternoon of day 2, so would have to be day 1 for me.

**Comment by sstevens2** [comment]
I'll go ahead and remove the evening social for this time around and in the post workshop debrief we can discuss if we liked the lunch socials and if we missed the evening social.
